### ISSUE TITLE
你好，反馈debian8 Python 2.7.9下一些问题

### ISSUE THREAD

**Issue by funders** [cnbeining/onedrivecmd#1]
python onedrivecmd.py list od:/
python onedrivecmd.py mkdir od:/xxx
## 都可以。

上传文件错误
 $python onedrivecmd.py put ./README.md od:/
Traceback (most recent call last):
  File "onedrivecmd.py", line 73, in <module>
    main()
  File "onedrivecmd.py", line 58, in main
    do_put(client, args)
  File "/data/onedrivecmd/utils/actions.py", line 263, in do_put
    client.item(drive="me", path=target_dir).upload_async(i)
## AttributeError: 'ItemRequestBuilder' object has no attribute 'upload_async'

列目录成功
 $python onedrivecmd.py list od:/
od:/test/       0       2016-09-27T07:56:32.000000Z
od:/xu06d.jpg   189001  2016-09-27T07:33:35.000000Z

下载文件错误
 $python onedrivecmd.py get od:/xu06d.jpg
Traceback (most recent call last):
  File "onedrivecmd.py", line 73, in <module>
    main()
  File "onedrivecmd.py", line 52, in main
    do_get(client, args)
  File "/data/onedrivecmd/utils/actions.py", line 156, in do_get
    item_info = get_item_temp_download_info(item)
  File "/data/onedrivecmd/utils/helper_item.py", line 65, in get_item_temp_download_info
    file_info['file']['hashes']['sha1Hash'].encode('utf-8'))
KeyError: 'sha1Hash'

安装了aria2加-hack下载也是出错
 $python onedrivecmd.py -hack get od:/xu06d.jpg
Traceback (most recent call last):
  File "onedrivecmd.py", line 73, in <module>
    main()
  File "onedrivecmd.py", line 52, in main
    do_get(client, args)
  File "/data/onedrivecmd/utils/actions.py", line 156, in do_get
    item_info = get_item_temp_download_info(item)
  File "/data/onedrivecmd/utils/helper_item.py", line 65, in get_item_temp_download_info
    file_info['file']['hashes']['sha1Hash'].encode('utf-8'))
KeyError: 'sha1Hash'

以上是在office365 onedrive for business测试，因为不懂py程序所以不知到底是什么问题。难道还要在office365后台设置什么？有时间看看。

```
```

**Comment by cnbeining** [comment]
算了，下个版本我上传彻底不用他内置的，下载API一定变了。

![image](https://cloud.githubusercontent.com/assets/1560962/18936026/23641d4a-85b2-11e6-82a0-b9a34daf51af.png)

下一版升级。

**Comment by cnbeining** [comment]
试一下新的版本？

**Comment by funders** [comment]
谢谢基友！

**Comment by funders** [comment]
init又出错了
python onedrivecmd.py init business
---------------------------------------------------
ATTENTION: This is for Onedrive Business and Office 365 only.
If you are using normal Onedrive, lease exit and run

onedrivecmd init

https://login.microsoftonline.com/common/oauth2/authorize?redirect_uri=https%3A%2F%2Fod.cnbeining.com&response_type=code&client_id=xxxxxxxxxxxxxx

Paste this URL into your browser, approve the app's access.
Copy all the code in the new window, and paste it below:
Paste code here: AxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxAA
Traceback (most recent call last):
  File "onedrivecmd.py", line 74, in <module>
    main()
  File "onedrivecmd.py", line 40, in main
    client = do_init(client, args)
  File "/data/onedrivecmd/utils/actions.py", line 127, in do_init
    client = init_business(client)
  File "/data/onedrivecmd/utils/actions.py", line 62, in init_business
    auth.authenticate(code, redirect_uri, client_secret_business, resource='https://api.office.com/discovery/')
  File "/usr/local/lib/python2.7/dist-packages/onedrivesdk/auth_provider.py", line 203, in authenticate
    data=params)
  File "/usr/local/lib/python2.7/dist-packages/onedrivesdk/http_provider.py", line 69, in send
    response = session.send(prepped)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 855, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string

**Comment by cnbeining** [comment]
这是requests包的问题。有可能OpenSSL和包的关系没有弄好。

参考https://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package/29099439#29099439 <https://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package/29099439#29099439> ：

pip install 'requests[security]'pyOpenSSL ndg-httpsclient pyasn1

你有可能需要python-dev libffi-dev libssl-dev 这3个包。 apt-get下。
