### ISSUE TITLE
这个是什么情况 能上传不能下载

### ISSUE THREAD

**Issue by hatvgit** [cnbeining/onedrivecmd#11]
root@debian-7-372187076-cp234:~# onedrivecmd get od:/speedtest.py  
Traceback (most recent call last):
  File "/usr/local/bin/onedrivecmd", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/onedrivecmd/onedrivecmd.py", line 61, in main
    do_get(client, args)
  File "/usr/local/lib/python2.7/dist-packages/onedrivecmd/utils/actions.py", line 213, in do_get
    bar.next()
  File "/usr/local/lib/python2.7/dist-packages/progress/__init__.py", line 73, in next
    self.update()
  File "/usr/local/lib/python2.7/dist-packages/progress/bar.py", line 33, in update
    filled_length = int(self.width * self.progress)
  File "/usr/local/lib/python2.7/dist-packages/progress/__init__.py", line 103, in progress
    return min(1, self.index / self.max)
ZeroDivisionError: division by zero

**Comment by cnbeining** [comment]
有点看不懂。。。难道文件长度是0？
