### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by GhostChild** [cnbeining/onedrivecmd#2]
I use ubuntu16.04server
run onedrivecmd put /home/hatsuyuki/download/ubuntu16.04/ubuntu-16.04-server-amd64.iso od:/
then it's error
I pasted the error code
by hatsuyuki
PS the command onedrivecmd I write in alias

`root@ubuntu:~# onedrivecmd put /home/hatsuyuki/download/ubuntu16.04/ubuntu-16.04-server-amd64.iso od:/
Traceback (most recent call last):
  File "/home/git/onedrivecmd/onedrivecmd.py", line 79, in <module>
    main()
  File "/home/git/onedrivecmd/onedrivecmd.py", line 61, in main
    do_put(client, args)
  File "/home/git/onedrivecmd/utils/actions.py", line 292, in do_put
    chunksize = int(args.chunk))
  File "/home/git/onedrivecmd/utils/uploader.py", line 72, in upload_self
    range_this=i, file_size= file_size)
  File "/home/git/onedrivecmd/utils/uploader.py", line 35, in upload_one_piece
    headers = headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 123, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 295, in prepare
    self.prepare_headers(headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 409, in prepare_headers
    check_header_validity(header)
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 800, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value 10485760 must be of type str or bytes, not <type 'int'>
`

**Comment by cnbeining** [comment]
![image](https://cloud.githubusercontent.com/assets/1560962/19628591/43aea12a-992f-11e6-9fd0-b783e1f94e46.png)

**Comment by cnbeining** [comment]
Fixed.

**Comment by GhostChild** [comment]
thank you
