### ISSUE TITLE
我快绝望了，上传失败，下载偶尔成功

### ISSUE THREAD

**Issue by sprders** [cnbeining/onedrivecmd#26]
### 上传不到1m的小文件svn.txt ，而且是英文命名的
> $ odcmd put /home/ubuntu/Downloads/svn.txt od:/
> _Path (/LiveFolders//svn.txt) contains invalid leading character._(报错)
### 上传文件名含有中文字符的pdf也报错，不到20m：

> Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/odcmd", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/onedrivecmd/onedrivecmd.py", line 67, in main
    do_put(client, args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/onedrivecmd/utils/actions.py", line 393, in do_put
    chunksize = int(args.chunk))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/onedrivecmd/utils/uploader.py", line 69, in upload_self
    api_url = api_base_url + 'drive/root:{dest_path}:/upload.createSession'.format(dest_path = dest_path)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 13: ordinal not in range(128)

### 不含有中文字符，大小就不到10m：
> $ odcmd get od:/SwitchyOmega_Chromium.crx ./

> Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/odcmd", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/onedrivecmd/onedrivecmd.py", line 61, in main
    do_get(client, args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/onedrivecmd/utils/actions.py", line 203, in do_get
    total_length = int(r.headers.get('content-length'))
TypeError: int() argument must be a string or a number, not 'NoneType'

### 下载含有中文字符的也报错：
> 报错同上

系统：Ubuntu 18.04 LTS
已绝望😞😞😞😞😞😞😞😞😞😞

**Comment by cnbeining** [comment]
试试Python 3版本？

pip3 install onedrivecmd ?

**Comment by sprders** [comment]
也不行，我已经放弃了。

**Comment by die-Deutsche-Orthopaedie** [comment]
又是蛋疼的python编码问题，试下将系统编码改成utf-8

**Comment by cnbeining** [comment]
以后我再也不手欠写Python 2/3兼容的东西了。

换Python3试试 系统设UTF8.
