### ISSUE TITLE
离线下载用不了

### ISSUE THREAD

**Issue by die-Deutsche-Orthopaedie** [cnbeining/onedrivecmd#28]
出错如下：
```
onedrivecmd remote http://xxxxxxx od:/Nein
Traceback (most recent call last):
  File "/usr/bin/onedrivecmd", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/onedrivecmd/onedrivecmd.py", line 85, in main
    do_remote(client, args)
  File "/usr/lib/python3.6/site-packages/onedrivecmd/utils/actions.py", line 525, in do_remote
    print(req.headers['location'])
  File "/usr/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```
API失效了吗？

**Comment by cnbeining** [comment]
有可能改了 但是离线下载只适用于个人API Office 365是没有的 自查一下？

**Comment by die-Deutsche-Orthopaedie** [comment]
好吧，看了源码才知道xD
然而个人版空间太小了，话说回来个人版离线完后有没有可能导入office365版

**Comment by cnbeining** [comment]
其实是很难的 因为一个是Onedrive 一个是SharePoint

然而共享再转存也许可以？没试过。。。

**Comment by die-Deutsche-Orthopaedie** [comment]
懒得折腾了，还是接着用VPS中转吧。。。速度还行，配合我写的那个递归上传文件夹脚本基本上可以不用管
