### ISSUE TITLE
SEARCH failed

### ISSUE THREAD

**Issue by ALEERQUESON2DIAS** [cnbeining/onedrivecmd#37]
All the files hosted in OneDrive have a file identification (fileid) that allows a faster download of them. Each time I upload a file I get it'ss fileid and store it in a database to facilitate the download.
I tried to get it with the SEARCH command but it is not working for me (Log at the end).
As an additional question ... can I use GET with a FILEID?
Thank you
Best regards
Ángel(ALQS2D)

A:\>onedrivecmd -conf A:/ODCMD/.onedrive.json list od:/ALQS2D/
od:/DAT/        52363505378     2015-01-02T10:45:26.853000Z
od:/FILE70se    225146  2019-01-13T06:51:08.250000Z
od:/FILEWITHOUTEXTENSION        18      2019-01-13T06:47:36.233000Z
od:/PRUEBA.txt  18      2019-01-13T02:15:27.403000Z

A:\>onedrivecmd -conf A:/ODCMD/.onedrive.json get od:/ALQS2D/PRUEBA.txt
←[KDownloading |################################| 100.0% - 0s
←[?25h
A:\>

A:\>onedrivecmd -conf A:/ODCMD/.onedrive.json search PRUEBA.txt
Traceback (most recent call last):
  File "C:\Python372\Scripts\onedrivecmd-script.py", line 11, in <module>
    load_entry_point('OnedriveCMD==0.1.6', 'console_scripts', 'onedrivecmd')()
  File "c:\python372\lib\site-packages\onedrivecmd\onedrivecmd.py", line 88, in main
    do_search(client, args)
  File "c:\python372\lib\site-packages\onedrivecmd\utils\actions.py", line 589, in do_search
    item_list = get_search_item_list_single_page_by_url_rec(requests_session, access_token, search_url, item_list = [])
  File "c:\python372\lib\site-packages\onedrivecmd\utils\helper_item.py", line 92, in get_search_item_list_single_page_by_url_rec
    for json_item in req.json()['value']:
KeyError: 'value'

**Comment by BearDic** [comment]
Thanks.

Can you tell me how frequent this problem appears? Every time, or randomly?

Yours,

**Comment by ALEERQUESON2DIAS** [comment]
Tank you. We abandoned this path and We are triying to use microsoft graph api directly.

Thans a lot for your answer.
