### ISSUE TITLE
error while run mkdir command

### ISSUE THREAD

**Issue by YQGong** [cnbeining/onedrivecmd#45]
error while run mkdir command

> onedrivecmd list od:/
od:/图片/       0       2019-03-20T11:09:22.270000Z
od:/文档/       0       2019-03-20T11:09:22.663000Z
od:/OneDrive 入门.pdf   1159342 2019-03-20T11:09:23.210000Z

> onedrivecmd mkdir od:/backups
Traceback (most recent call last):
  File "/usr/bin/onedrivecmd", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/onedrivecmd/onedrivecmd.py", line 79, in main
    do_mkdir(client, args)
  File "/usr/lib/python2.7/site-packages/onedrivecmd/utils/actions.py", line 447, in do_mkdir
    parent_id = req['id']
KeyError: u'id'

**Comment by BearDic** [comment]
Similar to #37. Will this happen every time you use 'mkdir'?

**Comment by YQGong** [comment]
> Similar to #37. Will this happen every time you use 'mkdir'?

yes everytime. And the error message is the same.

**Comment by BearDic** [comment]
In fact I'm planning to rewrite `mkdir` in a new way, but this problem is still notable. Please keep track on this issue, thank you!

**Comment by BearDic** [comment]
Is there an existing folder or file with the same name?

**Comment by YQGong** [comment]
no, actually this is a brand new account and you can see the dir structure in the return information of this command: 
`onedrivecmd list od:/
od:/图片/ 0 2019-03-20T11:09:22.270000Z
od:/文档/ 0 2019-03-20T11:09:22.663000Z
od:/OneDrive 入门.pdf 1159342 2019-03-20T11:09:23.210000Z`

**Comment by BearDic** [comment]
Please clone `https://github.com/BearDic/onedrivecmd` then install it. Make sure your installed version by `onedrivecmd --version` (should be `OnedriveCMD V0.1.7.1-dev`). This may provide more useful info. 

Thanks.
