### ISSUE TITLE
文件目录或文件名称有中文时，无法上传

### ISSUE THREAD

**Issue by colan1** [cnbeining/onedrivecmd#50]
[root@172 ~]# onedrivecmd put /root/Downloads od:/upload
Traceback (most recent call last):
  File "/usr/bin/onedrivecmd", line 11, in <module>
    load_entry_point('OnedriveCMD==0.1.8', 'console_scripts', 'onedrivecmd')()
  File "build/bdist.linux-x86_64/egg/onedrivecmd/onedrivecmd.py", line 68, in main
  File "build/bdist.linux-x86_64/egg/onedrivecmd/utils/actions.py", line 373, in do_put
  File "build/bdist.linux-x86_64/egg/onedrivecmd/utils/uploader.py", line 142, in upload_self
  File "build/bdist.linux-x86_64/egg/onedrivecmd/utils/uploader.py", line 142, in upload_self
  File "build/bdist.linux-x86_64/egg/onedrivecmd/utils/uploader.py", line 142, in upload_self
  File "build/bdist.linux-x86_64/egg/onedrivecmd/utils/uploader.py", line 80, in upload_self
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 3: ordinal not in range(128)

**Comment by DeSireFire** [comment]
要不你尝试一下，把文件转成utf8然后重命名文件再上传？

**Comment by BearDic** [comment]
感觉这种ascii编码报错很多都是python2和python3的问题...

**Comment by vyang127** [comment]
解决办法：
找到 onedrivecmd.py 文件，在前面加上

reload(sys)                     
sys.setdefaultencoding('utf-8')
