### ISSUE TITLE
上传目录失败

### ISSUE THREAD

**Issue by KirbyKFC** [cnbeining/onedrivecmd#54]
python版本3.7通过pip安装, 使用business账号登录
执行 onedrivecmd put /path/Artbook/ od:/Book/ 上传目录失败
在od:/Book/目录下新生成了一个0字节的文件(文件名~tmpF4_)

报错如下:
Uploading |################################| 100.0% - 0sTraceback (most recent call last):
  File "/usr/local/bin/onedrivecmd", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/onedrivecmd/onedrivecmd.py", line 67, in main
    do_put(client, args)
  File "/usr/local/lib/python3.7/dist-packages/onedrivecmd/utils/actions.py", line 393, in do_put
    chunksize = int(args.chunk))
  File "/usr/local/lib/python3.7/dist-packages/onedrivecmd/utils/uploader.py", line 101, in upload_self
    range_this = i, file_size = file_size, requests_session = requests_session)
  File "/usr/local/lib/python3.7/dist-packages/onedrivecmd/utils/uploader.py", line 33, in upload_one_piece
    file_piece = file_read_seek_len(source_file, range_this[0], content_length)
  File "/usr/local/lib/python3.7/dist-packages/onedrivecmd/utils/helper_file.py", line 38, in file_read_seek_len
    with open(filename, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/path/Artbook/'

**Comment by KirbyKFC** [comment]
发现最新版是0.1.8,通过pip安装的版本是0.1.6
我源码安装最新版再试试
