### ISSUE TITLE
Can't download folder

### ISSUE THREAD

**Issue by venssy** [cnbeining/onedrivecmd#56]
尝试下载one上面的文件夹时报错，现在是不支持文件夹下载吗？
分别用python2和python3装了一次，报错一样

`onedrivecmd get od:/vps/ ./bak/`
> Traceback (most recent call last):
  File "/usr/local/bin/onedrivecmd", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/onedrivecmd/onedrivecmd.py", line 61, in main
    do_get(client, args)
  File "/usr/local/lib/python3.5/dist-packages/onedrivecmd/utils/actions.py", line 173, in do_get
    item_info = get_item_temp_download_info(item)
  File "/usr/local/lib/python3.5/dist-packages/onedrivecmd/utils/helper_item.py", line 70, in get_item_temp_download_info
    file_info = convert_utf8_dict_to_dict(item.to_dict())
AttributeError: 'ChildrenCollectionPage' object has no attribute 'to_dict'

**Comment by BearDic** [comment]
您使用的版本并非最新. 我检查了 `actions.py` 和 `helper_item.py` 两个文件的更新历史, 发生上述报错的是**加入文件夹下载功能之前**的版本. 

最新版本是 0.1.8.1. 可以使用 PyPI 更新
```pip install --upgrade onedrivecmd ```

或者克隆代码到本地后执行
```python3 setup.py install```
