### ISSUE TITLE
onedrivecmd - impossible to use - onedrivesdk deprecated

### ISSUE THREAD

**Issue by andreabisello** [cnbeining/onedrivecmd#57]
Microsoft Windows [Versione 10.0.18362.329]
(c) 2019 Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\Andrea>pip -V
pip 19.0.3 from c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)

C:\Users\Andrea>pip install onedrivecmd
Requirement already satisfied: onedrivecmd in c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages (0.1.6)
Requirement already satisfied: progress in c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages (from onedrivecmd) (1.5)
Requirement already satisfied: onedrivesdk in c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages (from onedrivecmd) (2.0)
Requirement already satisfied: requests in c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages (from onedrivecmd) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages (from requests->onedrivecmd) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages (from requests->onedrivecmd) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages (from requests->onedrivecmd) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages (from requests->onedrivecmd) (2.8)
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Andrea>onedrivecmd
Traceback (most recent call last):
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\actions.py", line 10, in <module>
    from static import *
ModuleNotFoundError: No module named 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\uploader.py", line 12, in <module>
    from static import *
ModuleNotFoundError: No module named 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\onedrivecmd.py", line 8, in <module>
    from onedrivecmd.utils.actions import *
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\actions.py", line 17, in <module>
    from .uploader import *
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\uploader.py", line 18, in <module>
    from .helper_item import *
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\helper_item.py", line 7, in <module>
    import onedrivesdk
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivesdk\__init__.py", line 6, in <module>
    raise ImportError(MESSAGE)
ImportError: 'onedrivesdk' has been deprecated.
Visit https://pypi.org/project/onedrivesdk for migration information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\actions.py", line 10, in <module>
    from static import *
ModuleNotFoundError: No module named 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\uploader.py", line 12, in <module>
    from static import *
ModuleNotFoundError: No module named 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37-32\Scripts\onedrivecmd-script.py", line 11, in <module>
    load_entry_point('OnedriveCMD==0.1.6', 'console_scripts', 'onedrivecmd')()
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\onedrivecmd.py", line 16, in <module>
    from .utils.actions import *
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\actions.py", line 17, in <module>
    from .uploader import *
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\uploader.py", line 18, in <module>
    from .helper_item import *
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivecmd\utils\helper_item.py", line 7, in <module>
    import onedrivesdk
  File "c:\users\andrea\appdata\local\programs\python\python37-32\lib\site-packages\onedrivesdk\__init__.py", line 6, in <module>
    raise ImportError(MESSAGE)
ImportError: 'onedrivesdk' has been deprecated.
Visit https://pypi.org/project/onedrivesdk for migration information.

C:\Users\Andrea>

**Comment by cnbeining** [comment]
This project need to be rewritten.

Andrea Bisello <notifications@github.com>于2019年9月9日 周一上午4:03写道：

**Comment by cnbeining** [comment]
Fixed - please update.

**Comment by cxumol** [comment]
got the same issue today, by either `pip install --force-reinstall --upgrade onedrivecmd` or `pip install --force-reinstall -U git+https://github.com/cnbeining/onedrivecmd.git`

**Comment by andreabisello** [comment]
@cnbeining  
please, can you deploy the fix?
many thanks.

**Comment by andreabisello** [comment]
@cnbeining please,
i would like to use this command line tool. can you deploy the fix? thanks.

**Comment by BearDic** [comment]
If `git clone ...` and `python3 setup.py install` work then just use it...

**Comment by Kolobaka** [comment]
@andreabisello problem is in onedrivesdk
pip install --force-reinstall onedrivesdk==1.1.8
really fixes it, because onedrivesdk >= 2.0.0 is depricated
