### ISSUE TITLE
centos7 安装出错了

### ISSUE THREAD

**Issue by Ks236** [cnbeining/onedrivecmd#58]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-TVAtBr/onedrivesdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-TVAtBr/onedrivesdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-TVAtBr/onedrivesdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-TVAtBr/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by zypy333** [comment]
我也是，后来解决了吗

**Comment by lhotakj** [comment]
Hello,
I'm having the same issue on Ubuntu 20.04 with Python 2.7 and Python 3.8
```
jarda@ubuntu:~$ python2.7 --version
Python 2.7.18
jarda@ubuntu:~$ pip2.7 install onedrivecmd
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting onedrivecmd
  Using cached OnedriveCMD-0.1.8.1.tar.gz (33 kB)
Collecting progress
  Using cached progress-1.5.tar.gz (5.8 kB)
Collecting onedrivesdk
  Using cached onedrivesdk-2.0.tar.gz (1.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-imnMuW/onedrivesdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-imnMuW/onedrivesdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ehhY9h
         cwd: /tmp/pip-install-imnMuW/onedrivesdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-imnMuW/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
jarda@ubuntu:~$ 

```
or
```
jarda@ubuntu:~$ python3.8 --version
Python 3.8.5
jarda@ubuntu:~$ pip3.8 install onedrivecmd
Defaulting to user installation because normal site-packages is not writeable
Collecting onedrivecmd
  Using cached OnedriveCMD-0.1.8.1.tar.gz (33 kB)
Collecting progress
  Using cached progress-1.5.tar.gz (5.8 kB)
Collecting onedrivesdk
  Using cached onedrivesdk-2.0.tar.gz (1.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v982un6o/onedrivesdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v982un6o/onedrivesdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0lvlhv6l
         cwd: /tmp/pip-install-v982un6o/onedrivesdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v982un6o/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    NotADirectoryError: [Errno 20] Not a directory: '/tmp/pip-install-v982un6o/onedrivesdk/setup.py/../NOTICE.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
any sugeestion please?

**Comment by lhotakj** [comment]
Oh yes, found it just a few secs after - https://github.com/OneDrive/onedrive-sdk-python/issues/167
@Ks236 the solution works.
@cnbeining I guess you can close this issue ;) thanks
