### ISSUE TITLE
init_business error

### ISSUE THREAD

**Issue by TypicalSEE** [cnbeining/onedrivecmd#69]
Hi, I was using onedrivecmd to upload a file to Onedrive for business. But command "onedrivecmd init_business" doesn't work. The info is as follows:

$ onedrivecmd init_business
ATTENTION: This is for Onedrive Business and Office 365 only.
If you are using normal Onedrive, lease exit and run

onedrivecmd init

https://login.microsoftonline.com/common/oauth2/authorize?client_id=6fdb55b4-c905-4612-bd23-306c3918217c&response_type=code&redirect_uri=https%3A%2F%2Fod.cnbeining.com

Paste this URL into your browser, approve the app's access.
Copy all the code in the new window, and paste it below:
Paste code here: AQABAAIAAAAm-06blBE1TpVMil8KPQ41jtRufwLVWZ23d1o1HEDflVBRw2OBD5qTDPXmx2zkcLTbajfwsnEbfup1Yi9RRqYVPlK5E6YcfHkJyiSyQ6bGnuSt53FIVCa1lrg_SGQpCDjQM069KZYUqo2Xw6QXy4mUdqVH4t7-Mne0FGOLzLbuPSv9rsPuM3ivTi_A79H1WlBXRqPArm-O_96xcVsk01vkV38aG7fB8QvBM8LXqm5IYPVUSyCGoH3
YvwVCRKDCKl91RjYWvt4_D9vg2kKSrk9HezVae9ud224T45TiyRKBgVRsatFhrmfURFgQSe0_aoBP6ANn4cYxFh3ulUYAxjcdAqVN_9zsEec1wTUeOgkDvnuJMql77bo924IbwYdchrRMDzEN25ZLfyVVXP_Fwp4YJy_m64-nQdN8daxkfu6kZCbCdYVyy2FfXVozAtaFRvP136JnQ9WEjmrWb1dECoAPNxyXQpWgyTM_1nIAiAbtVpgY7vfF0EGDupASzhTNayue_1O
6ZiA8OxpYBb0PDDViYnsd9TwkbL-WHEe_Fagw86NTOIu_iEXx5qmjWeuIE1NAv03cpgrA1KSOafH5bXtyTwGm8dgGPbqT1DF0MAYvVrESeuzgc1qA-dAigmHONOYfV2jGW1ddFod4ygtGbEhNJgHSz_xrYDSV6DD5tP-t3XmVAZLDVm9NkO13tsnrcT4gAA
Traceback (most recent call last):
  File "/home/CAM/yliu/.python3/bin/onedrivecmd", line 11, in <module>
    load_entry_point('OnedriveCMD==0.1.8.1', 'console_scripts', 'onedrivecmd')()
  File "/home/CAM/yliu/.python3/lib/python3.6/site-packages/OnedriveCMD-0.1.8.1-py3.6.egg/onedrivecmd/onedrivecmd.py", line 47, in main
  File "/home/CAM/yliu/.python3/lib/python3.6/site-packages/OnedriveCMD-0.1.8.1-py3.6.egg/onedrivecmd/utils/actions.py", line 149, in do_init
  File "/home/CAM/yliu/.python3/lib/python3.6/site-packages/OnedriveCMD-0.1.8.1-py3.6.egg/onedrivecmd/utils/actions.py", line 87, in init_business
  File "/projects/EBP/Goffinet_Atrichum/Python-3.6.5/lib/python3.6/site-packages/onedrivesdk/helpers/resource_discovery.py", line 25, in get_service_info
    response = json.loads(requests.get(self._discovery_service_url, headers=headers).text)
  File "/projects/EBP/Goffinet_Atrichum/Python-3.6.5/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/projects/EBP/Goffinet_Atrichum/Python-3.6.5/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/EBP/Goffinet_Atrichum/Python-3.6.5/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

How can I solve this problem? Thanks in advance!

**Comment by Flyfish233** [comment]
Same on 0.1.8
Traceback (most recent call last):
  File "/usr/local/bin/onedrivecmd", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/onedrivecmd/onedrivecmd.py", line 47, in main
    client = do_init(client, args)
  File "/usr/local/lib/python3.7/dist-packages/onedrivecmd/utils/actions.py", line 149, in do_init
    client = init_business(client)
  File "/usr/local/lib/python3.7/dist-packages/onedrivecmd/utils/actions.py", line 87, in init_business
    service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]
  File "/usr/local/lib/python3.7/dist-packages/onedrivesdk/helpers/resource_discovery.py", line 25, in get_service_info
    response = json.loads(requests.get(self._discovery_service_url, headers=headers).text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
