### ISSUE TITLE
上传日文文件(或含有特殊字符)错误

### ISSUE THREAD

**Issue by ACGunion** [cnbeining/onedrivecmd#7]
```
[root@161068 onedrivecmd]# python3 onedrivecmd.py put /var/lib/transmission/Downloads/00/[SOME_JAPANESE].rar  od:/
Traceback (most recent call last):
  File "onedrivecmd.py", line 9, in <module>
    from utils.actions import * 
  File "/root/onedrivecmd/utils/actions.py", line 8, in <module>
    from static import * 
ModuleNotFoundError: No module named 'static'
[root@161068 onedrivecmd]# python onedrivecmd.py put /var/lib/transmission/Downloads/00/[SOME_JAPANESE].rar  od:/
Traceback (most recent call last):
  File "onedrivecmd.py", line 79, in <module>
    main()
  File "onedrivecmd.py", line 61, in main
    do_put(client, args)
  File "/root/onedrivecmd/utils/actions.py", line 300, in do_put
    chunksize = int(args.chunk))
  File "/root/onedrivecmd/utils/uploader.py", line 60, in upload_self
    api_url = api_base_url + 'drive/root:{dest_path}:/upload.createSession'.format(dest_path = dest_path)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 12: ordinal not in range(128)
```
OneDrive For Business 
请不要在意上传的内容..
我是用的是python2.7.5 也就是centos7默认的样子.没有学过python,貌似是字符编码的问题?
如果需要for business账户进行debug我可以提供.

**Comment by cnbeining** [comment]
的确是编码的坑。

也许我一开始应该用Python3的。。

2017年6月4日 上午2:33，"Kung" <notifications@github.com>写道：

**Comment by cnbeining** [comment]
重新搞了下 请测试。

**Comment by BearDic** [comment]
no more updates
