### ISSUE TITLE
ubuntu18安装时报错

### ISSUE THREAD

**Issue by wangebcjd** [cnbeining/onedrivecmd#75]
用的pip install onedrivecmd。直接就报错了。
pip是正常的，可以pip install 其它程序，有python3。

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wpktvtbt/onedrivesdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wpktvtbt/onedrivesdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-al24kpva
         cwd: /tmp/pip-install-wpktvtbt/onedrivesdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wpktvtbt/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    NotADirectoryError: [Errno 20] Not a directory: '/tmp/pip-install-wpktvtbt/onedrivesdk/setup.py/../NOTICE.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mvpbang** [comment]
use onedrivesdk 1.1.8, do't use lasted!
