### ISSUE TITLE
onedrivecmd init 时报错

### ISSUE THREAD

**Issue by AuTsing** [cnbeining/onedrivecmd#76]
Traceback (most recent call last):
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\actions.py", line 11, in <module>
    from static import *
ModuleNotFoundError: No module named 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\uploader.py", line 13, in <module>
    from static import *
ModuleNotFoundError: No module named 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\onedrivecmd.py", line 8, in <module>
    from onedrivecmd.utils.actions import *
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\actions.py", line 20, in <module>
    from .uploader import *
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\uploader.py", line 21, in <module>
    from .helper_item import *
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\helper_item.py", line 7, in <module>
    import onedrivesdk
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivesdk\__init__.py", line 6, in <module>
    raise ImportError(MESSAGE)
ImportError: 'onedrivesdk' has been deprecated.
Visit https://pypi.org/project/onedrivesdk for migration information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\actions.py", line 11, in <module>
    from static import *
ModuleNotFoundError: No module named 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\uploader.py", line 13, in <module>
    from static import *
ModuleNotFoundError: No module named 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tsing\AppData\Local\Programs\Python\Python38\Scripts\onedrivecmd-script.py", line 33, in <module>
    sys.exit(load_entry_point('OnedriveCMD==0.1.8.1', 'console_scripts', 'onedrivecmd')())
  File "C:\Users\tsing\AppData\Local\Programs\Python\Python38\Scripts\onedrivecmd-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\onedrivecmd.py", line 17, in <module>
    from .utils.actions import *
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\actions.py", line 20, in <module>
    from .uploader import *
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\uploader.py", line 21, in <module>
    from .helper_item import *
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivecmd\utils\helper_item.py", line 7, in <module>
    import onedrivesdk
  File "c:\users\tsing\appdata\local\programs\python\python38\lib\site-packages\onedrivesdk\__init__.py", line 6, in <module>
    raise ImportError(MESSAGE)
ImportError: 'onedrivesdk' has been deprecated.
Visit https://pypi.org/project/onedrivesdk for migration information.

请问该如何解决？

**Comment by EamonZJX** [comment]
I met this error too.

**Comment by ethanjyx** [comment]
Same error
