### ISSUE TITLE
求助，win10系统下运行报错

### ISSUE THREAD

**Issue by cheeseyang** [cnbeining/onedrivecmd#77]
PS E:\win64> onedrivecmd
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\actions.py", line 13, in <module>
    from helper_file import *
ModuleNotFoundError: No module named 'helper_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\uploader.py", line 14, in <module>
    from helper_file import *
ModuleNotFoundError: No module named 'helper_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\onedrivecmd\onedrivecmd.py", line 8, in <module>
    from onedrivecmd.utils.actions import *
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\actions.py", line 20, in <module>
    from .uploader import *
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\uploader.py", line 21, in <module>
    from .helper_item import *
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\helper_item.py", line 7, in <module>
    import onedrivesdk
  File "c:\program files\python37\lib\site-packages\onedrivesdk\__init__.py", line 6, in <module>
    raise ImportError(MESSAGE)
ImportError: 'onedrivesdk' has been deprecated.
Visit https://pypi.org/project/onedrivesdk for migration information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\actions.py", line 13, in <module>
    from helper_file import *
ModuleNotFoundError: No module named 'helper_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\uploader.py", line 14, in <module>
    from helper_file import *
ModuleNotFoundError: No module named 'helper_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\Scripts\onedrivecmd-script.py", line 11, in <module>
    load_entry_point('OnedriveCMD==0.1.8.1', 'console_scripts', 'onedrivecmd')()
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files\python37\lib\site-packages\onedrivecmd\onedrivecmd.py", line 17, in <module>
    from .utils.actions import *
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\actions.py", line 20, in <module>
    from .uploader import *
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\uploader.py", line 21, in <module>
    from .helper_item import *
  File "c:\program files\python37\lib\site-packages\onedrivecmd\utils\helper_item.py", line 7, in <module>
    import onedrivesdk
  File "c:\program files\python37\lib\site-packages\onedrivesdk\__init__.py", line 6, in <module>
    raise ImportError(MESSAGE)
ImportError: 'onedrivesdk' has been deprecated.
Visit https://pypi.org/project/onedrivesdk for migration information.

**Comment by StrollStars** [comment]
我这边也有这个问题，在路径下就是找不到，希望作者能出个二进制版本。
