### ISSUE TITLE
无法下载含有中文名字的文件或文件夹

### ISSUE THREAD

**Issue by redapple0204** [cnbeining/onedrivecmd#8]
使用python3版本提示
>redapple@redapple-System-Product-Name ~> onedrivecmd -hack get od:/文档.docx
Traceback (most recent call last):
  File "/usr/local/bin/onedrivecmd", line 11, in <module>
    load_entry_point('OnedriveCMD==0.1.3', 'console_scripts', 'onedrivecmd')()
  File "/usr/local/lib/python3.5/dist-packages/onedrivecmd/onedrivecmd.py", line 61, in main
    do_get(client, args)
  File "/usr/local/lib/python3.5/dist-packages/onedrivecmd/utils/actions.py", line 188, in do_get
    execute_cmd(cmd)
  File "/usr/local/lib/python3.5/dist-packages/onedrivecmd/utils/helper_file.py", line 27, in execute_cmd
    os.system(cmd.decode("utf-8").encode(sys.stdout.encoding))
AttributeError: 'str' object has no attribute 'decode'
redapple@redapple-System-Product-Name ~>

python2提示

>redapple@redapple-System-Product-Name ~> onedrivecmd -hack get od:/文档.docx
Traceback (most recent call last):
  File "/usr/local/bin/onedrivecmd", line 9, in <module>
    load_entry_point('OnedriveCMD==0.1.3', 'console_scripts', 'onedrivecmd')()
  File "/usr/local/lib/python2.7/dist-packages/onedrivecmd/onedrivecmd.py", line 61, in main
    do_get(client, args)
  File "/usr/local/lib/python2.7/dist-packages/onedrivecmd/utils/actions.py", line 161, in do_get
    item = get_remote_item(client, path = f)
  File "/usr/local/lib/python2.7/dist-packages/onedrivecmd/utils/helper_item.py", line 31, in get_remote_item
    f = client.item(drive='me', path = path).get()
  File "/usr/local/lib/python2.7/dist-packages/onedrivesdk/extensions/one_drive_client_helper.py", line 49, in item
    return drive_builder.item_by_path(path)
  File "/usr/local/lib/python2.7/dist-packages/onedrivesdk/extensions/drive_request_builder_helper.py", line 41, in item_by_path
    return ItemRequestBuilder(self.append_to_request_url("root:/"+str(path)+":"), self._client)
  File "/usr/local/lib/python2.7/dist-packages/onedrivesdk/request_builder_base.py", line 48, in append_to_request_url
    return self._request_url + "/" + url_segment
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 6: ordinal not in range(128)
redapple@redapple-System-Product-Name ~> 

去不去掉-hack都一样

**Comment by cnbeining** [comment]
试试新版本？

**Comment by BearDic** [comment]
no more updates
