### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by root0day** [cnbeining/onedrivecmd#81]
环境
root@HKG-BLBL:~# cat /etc/issue
Debian GNU/Linux 10 \n \l

root@HKG-BLBL:~# python --version
Python 2.7.16
root@HKG-BLBL:~# python3 --version
Python 3.7.3
root@HKG-BLBL:~# 

报错信息
root@HKG-BLBL:~# pip install onedrivecmd
Collecting onedrivecmd
  Using cached https://files.pythonhosted.org/packages/2a/bd/162f2536876076a075a2c1dd117a48cdd7a3cf07df0338bc0f2cf5d13ffb/OnedriveCMD-0.1.8.1.tar.gz
Collecting onedrivesdk (from onedrivecmd)
  Using cached https://files.pythonhosted.org/packages/b3/76/9a3fe5b36079f5c40b33c89ad6f7737e3b8609010a80c9ed24d762ddb93e/onedrivesdk-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-H3Sjfv/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-H3Sjfv/onedrivesdk/
root@HKG-BLBL:~# 

截图
![image](https://user-images.githubusercontent.com/26130494/125242279-102fee00-e31f-11eb-9c71-0fd618967920.png)

**Comment by arisliang** [comment]
不止init，直接运行`onedrivecmd` 也是这个错误。

>OnedriveCMD            0.1.8.1
onedrivesdk            2.0.1

python 3.9.10
windows 10
