### ISSUE TITLE
离线下载出错

### ISSUE THREAD

**Issue by lizongzeshunshun** [cnbeining/onedrivecmd#9]
账户是商业版E3订阅（Onedrive for business）

```
root@ubuntu:~/onedrive-cli-test-folder/onedrivecmd# python3 onedrivecmd.py remote "http://thecatapi.com/api/images/get?format=src&type=gif"
Traceback (most recent call last):
  File "onedrivecmd.py", line 79, in <module>
    main()
  File "onedrivecmd.py", line 73, in main
    do_remote(client, args)
  File "/root/onedrive-cli-test-folder/onedrivecmd/utils/actions.py", line 446, in do_remote
    print(req.headers['location'])
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```

**Comment by cnbeining** [comment]
请升级到最新版，而且：

只有个人版支持离线下载。

**Comment by lizongzeshunshun** [comment]
@cnbeining 嗯，刚刚已经看到了
